image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
sources:
  - git@git.sr.ht:~mmagueta/relational-engine
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - check_branch: |
      cd relational-engine
      if [ "$(git rev-parse master)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - build: |
      cd relational-engine
      nix flake check